# Generated by Django 5.0.6 on 2024-07-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance_after_borrow', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance_after_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('history_type', models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Borrow', 'Borrow'), ('Return', 'Return')], max_length=10, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.useraccount')),
            ],
            options={
                'ordering': ['return_date'],
            },
        ),
    ]
